### ISSUE TITLE
SimpleBuilder `natToInteger` and `integerToReal` implementations are apparently wrong

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/crucible#18]
I came across some suspicious code while browsing module `Lang.Crucible.Solver.SimpleBuilder`:
```
  natToInteger sym x
    | NatElt n l <- x = return $! IntElt (toInteger n) l
    | Just (IntegerToNat y) <- asApp x = return y
    | otherwise = sbMakeElt sym (NatToInteger x)

  integerToReal sym x
    | IntElt i l <- x = return $! RatElt (toRational i) l
    | Just (RealToInteger y) <- asApp x = return y
    | otherwise  = sbMakeElt sym (IntegerToReal x)
```
I had assumed that `natToInteger` should always return a non-negative integer, and `integerToReal` should always return a whole number. But if a negative integer was passed to `integerToNat`, and the result was passed to `natToInteger`, then we would get the original negative integer back! Similarly, passing a fractional real number to `realToInteger` followed by `integerToReal` would give the original fractional real number.

Does it make any sense to do this?

**Comment by joehendrix** [comment]
This is by design, and allowed by the definition of integerToNat:

```
-- | Convert an integer to a natural number.
--
-- For negative integers, the result is undefined.
integerToNat :: sym -> SymInteger sym -> IO (SymNat sym)
```

If one wants to assert that an integer I is a nat before converting it, then it's appropriate to an explicit assertion I >= 0.

Arguably the API as written could lead to errors, but I prefer to leave it up to people writing compilers from their language into crucible to figure out how to best handle conversion errors at the language level without automatically introducing a case split on whether a symbolic integer is positive at the solver API level.

**Comment by brianhuffman** [comment]
So "undefined" here doesn't mean an arbitrary/unspecified natural number, but rather "undefined" in the sense of C undefined behavior, is this right?

If that's so, then I suppose that we make no guarantees whatsoever about the return value of `natToInteger` (or any other function for that matter) if it is given an undefined argument.

**Comment by joehendrix** [comment]
If I were to define the intended semantics in terms of a single model, then I'd say the underlying set denoted by NatType consists of the natural numbers, and an infinite set of unknown constants.  Quantifiers and symbolic variables are over the natural numbers, but the underlying set contains more elements.

This trick is used in the SMT community when dealing with finite types since the underlying Nelson-Oppen combination only works for stably infinite theories.  SMT is over all models rather than a single model, so the context is a bit different though.

So "integerToNat -1" has to denote some value in the set, but not necessarily a natural number.  This means that it should always return the same value, but the value is unspecified.
