### ISSUE TITLE
Support bitvector rotations in what4

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/crucible#182]
Currently what4 provides shift operations for bitvector types, but not rotates. A rotate can be expressed in terms of left-shift, a right-shift, and an or/xor; however, this encoding obscures combinations of rotates that we'd like to be able to simplify.

If we make rotates into a primitive operation in what4, we can implement a bunch of nice simplification rules for them; we can also directly generate rotation operations in those backends that support them (e.g. SAW).

Better support for rotates would be particularly helpful for reasoning about ARX crypto algorithms, which are built from additions, rotations, and xor.

**Comment by travitch** [comment]
I believe @dmwit looked at this.  My (possibly incorrect) recollection is that we ran into trouble because SMTLib2 rotates only support a rotate amount by a fixed integer and we wanted to keep what4 as close to SMTLib as possible.

We could change that stance and support rotation by a symbolic value and use SMTLib rotate when possible, or desugar to shifts and ors otherwise.

This would make some code in semmc nicer.

**Comment by robdockins** [comment]
Indeed, there's no direct SMTLib2 translation in the general case.  @brianhuffman has convinced me that adding rotates to What4 is worth it for benefits of being able to round-trip through SAWCore, and for the simplifications it would enable.
