### ISSUE TITLE
Regression in crux-llvm improvements merged PR

### ISSUE THREAD

**Issue by kquick** [GaloisInc/crucible#385]
The merge of https://github.com/GaloisInc/crucible/pull/375 introduced a test regression for both the string and string2 tests in crux-llvm.

These tests are not run by travis, but they are run by fryingpan and can be seen at http://fryingpan.dev.galois.com/hydra/build/399547.

The string test dropped from "Total: 2, Proved: 2" to "Total: 1, Proved: 1".
The string2 test dropped from "Total: 3, Proved: 3" to "Total: 2, Proved: 2".

**Comment by robdockins** [comment]
I'm willing to bet this one instantiation of #335.  I don't see any way for the number of goals to change like that between one setup and other unless the input program is different, which suggests to me that different clang versions are producing slightly different bitcode outputs.

**Comment by atomb** [comment]
I think that this is, by definition, an instance of testing suite fragility, since changes in the number of goals generated  can also happen any time `what4` or `crucible` change in any non-trivial way. Different simplification rules in `what4`, for instance, could cause the number of goals that are automatically discharged (and therefore never reported) to change.

I think this case, though, is an instance of `clang` version differences, since the tests pass locally for me. 

Fundamentally, the success or failure of these tests shouldn't depend on how many goals are generated. Having a goal go from disproved to proved, or vice versa, is relevant, however.  Getting the test suite to understand the difference between those cases could be a little bit of work.

Should we consider making that change to be the condition on closing this issue?

**Comment by robdockins** [comment]
We could add a "quiet" mode or something that would suppress those details and just print out the overall verdict, that would probably reduce these kinds of errors a fair amount.

**Comment by atomb** [comment]
Yeah, I like that idea.

**Comment by robdockins** [comment]
I believe this is fixed in #395
