### ISSUE TITLE
Make crux-llvm header and library bitcode files easier to find when using releases

### ISSUE THREAD

**Issue by atomb** [GaloisInc/crucible#731]
Currently, `crux-llvm` expects `crucible.h`, any C++ library bitcode files, and runtime support files for executable counterexamples to exist in a `c-src` subdirectory of the library directory. The `libdir` configuration variable can control where to look for these files, but its default value is only meaningful when the executables we build are located somewhere that Cabal understands. When we distribute binary tarballs, this isn't true, so users need to specify a value for `libdir` manually.

**Comment by kquick** [comment]
The manual specification is done via the `crux_llvm_libdir` environment variable or via the `lib-dir` configuration file parameter.  The `include-dirs` configuration file parameter or the `-I` or `--include-dirs` command-line parameters can also be used for finding the include files (but not the `.bc` files).

**Comment by RyanGlScott** [comment]
> The manual specification is done via the `crux_llvm_libdir` environment variable

`crux_llvm_datadir`, you mean?

**Comment by atomb** [comment]
Yeah, the Cryptol approach would probably work nicely.

Cryptol also bakes those files into the executable, so it doesn't need them to exist in the file system (but copies in the file system override those baked in). That won't work for header and bitcode files, though.

**Comment by kquick** [comment]
I did mean `crux_llvm_datadir` (confusing, because that is the basis for the `lib-dir` configuration file value).

Re: the cryptol code referenced:
* Line 117 matches what `cabal install --enable-relocatable` would do.  
* The `getAppUserDataDirectory` would be a user's specific config files; that's a nice enhancement but unlikely to help find files provided with the binary distribution.

I think the issue may be in the `bundle_crux_llvm_files` in the CI; it's manually extracting and placing the files.  This isn't reflected in the `getDataDir` (especially in a non-relocatable build) and I think the placement location needs to be in a data subdir.  Perhaps re-working the CI to use `cabal install --enable-relocatable` to generate the binary distribution would help here.

**Comment by RyanGlScott** [comment]
I like the idea of `--enable-relocatable`, but in practice, I can't seem to get it to actually work. I tried building `crux-llvm` with `--enable-relocatable`, but I didn't observe any difference in behavior. Moreover, inspecting the autogenerated `Paths_crux_llvm.hs` file reveals that it's still hardcoding the path in `crux_llvm_datadir`. Perhaps this is a [known bug](https://github.com/haskell/cabal/issues/5551)? Perhaps I'm just doing it wrong?

**Comment by RyanGlScott** [comment]
I decided to give the Cryptol approach (i.e., searching a directory relative to the executable path) a try. The basic idea would be to generalize `crux-llvm`'s `libDir` command-line option to take multiple paths instead of just one:

```diff
diff --git a/crux-llvm/src/Crux/LLVM/Config.hs b/crux-llvm/src/Crux/LLVM/Config.hs
index 03270c95..ed42f75c 100644
--- a/crux-llvm/src/Crux/LLVM/Config.hs
+++ b/crux-llvm/src/Crux/LLVM/Config.hs
@@ -56,7 +56,7 @@ data LLVMOptions = LLVMOptions
   { clangBin   :: FilePath
   , linkBin    :: FilePath
   , clangOpts  :: [String]
-  , libDir     :: FilePath
+  , libDirs    :: [FilePath]
   , incDirs    :: [FilePath]
   , targetArch :: Maybe String
   , ubSanitizers :: [String]
@@ -85,8 +85,9 @@ llvmCruxConfig = do
                                     (Crux.oneOrList Crux.stringSpec) []
                       "Additional options for `clang`."
 
-         libDir <- Crux.section "lib-dir" Crux.dirSpec libDirDefault
-                   "Locations of `crux-llvm` support library."
+         libDirs <- Crux.section "lib-dir"
+                        (Crux.oneOrList Crux.dirSpec) [libDirDefault, {- Directory relative to executable path -}]
+                    "Locations of `crux-llvm` support library."
 
          incDirs <- Crux.section "include-dirs"
                         (Crux.oneOrList Crux.dirSpec) []
```

There are three parts of the code that would have to be updated to accommodate this change:

1. https://github.com/GaloisInc/crucible/blob/79428012dae4e3c922f75c6f41f418c8aacca665/crux-llvm/src/Crux/LLVM/Compile.hs#L133-L135
2. https://github.com/GaloisInc/crucible/blob/79428012dae4e3c922f75c6f41f418c8aacca665/crux-llvm/src/Crux/LLVM/Compile.hs#L263-L265
3. https://github.com/GaloisInc/crucible/blob/79428012dae4e3c922f75c6f41f418c8aacca665/crux-llvm/src/Crux/LLVM/Compile.hs#L166

Updating (1) and (2) would be simple, as it would be tantamount to generating multiple `-I <path>` arguments instead of just one. Updating (3) will be trickier, however, as `crux-llvm` is passing a path to a specific `libcxx*.bc` file directly to `clang`. I'm unclear if there is a way to make `clang` look through multiple paths when finding input files such as `*.bc` files.

**Comment by RyanGlScott** [comment]
Unfortunately, I don't think the idea in https://github.com/GaloisInc/crucible/issues/731#issuecomment-846040643 will pan out in the end, as we really do need to find one _specific_ directory where `c-src` lives. (As opposed to the `-I`/`-L` approach, where we can list multiple directories and let the compiler do the rest.) In light of this, the most straightforward approach (as I see it) would be to search different locations when determining the default `lib-dir`, picking the first one that it knows to exist. If all else fails, fall back to `getDataDir`. This is the approach that I went with in #746.

**Comment by RyanGlScott** [comment]
#746 makes the status quo more tolerable by making `crux-llvm` look for the `lib-dir` relative to the executable path, and if it doesn't find it there, default to `cabal`'s `getDataDir`. As a result, this fixes the bindist use, so I've closed this issue. If someone can figure out how to make `cabal`'s `--enable-relocatable` flag work, however, do feel free to reopen this, as that offers a much cleaner way to do this whole song and dance.
