### ISSUE TITLE
GHC 9.0.1Support

### ISSUE THREAD

**Issue by joehendrix** [GaloisInc/crucible#732]
I'd like Crucible to support GHC 9.0.1, but did not see a ticket for that.

**Comment by RyanGlScott** [comment]
In particular, see GaloisInc/what4#110, which is blocked on snapframework/io-streams#76.

**Comment by RyanGlScott** [comment]
Now that GaloisInc/what4#110 is merged, here are the remaining blockers:

* [`cryptohash-sha1`](https://hackage.haskell.org/package/cryptohash-sha1) has too restrictive of an upper version bound on `base`.
* Due to [a GHC bug](https://gitlab.haskell.org/ghc/ghc/-/issues/19397), I had to employ a somewhat unpleasant workaround to make two of the executable components compile. It might be worth waiting until GHC 9.0.2, which features a fix for this bug.

**Comment by robdockins** [comment]
Following the release of 9.0.2, I think we ended up fixing this.

**Comment by RyanGlScott** [comment]
Oops, I forgot to follow up on this issue. Indeed, #948 fixed this.
