### ISSUE TITLE
Crash! GlobalState.globalMuxFn

### ISSUE THREAD

**Issue by max-orhai** [GaloisInc/crucible#75]
Using crucible via SAW, I encountered this:

```
%< --------------------------------------------------- 
  Revision:  2672c2252aefeb8027b93652d2b90f076d44d819
  Branch:    HEAD
  Location:  GlobalState.globalMuxFn
  Message:   Attempting to merge global states of incorrect branch depths:
              *** Depth 1:  2
              *** Depth 2:  1
              *** Location: internal
CallStack (from HasCallStack):
  panic, called at src/Lang/Crucible/Panic.hs:11:9 in crucible-0.4-5GF7fggLRYiAfjp8EgEf8:Lang.Crucible.Panic
  panic, called at src/Lang/Crucible/Simulator/GlobalState.hs:208:6 in crucible-0.4-5GF7fggLRYiAfjp8EgEf8:Lang.Crucible.Simulator.GlobalState
%< --------------------------------------------------- 
```
I can provide a test case (sawscript and llvm) if you'd like.

**Comment by robdockins** [comment]
Test case would be helpful.

**Comment by robdockins** [comment]
I'm not able to reproduce this issue using head SAW.  Are you still having trouble?

$ saw --version
0.2 (6c55176)

**Comment by max-orhai** [comment]
I still have the same crash, using last night's SAW build (e61d1b4).

**Comment by robdockins** [comment]
I've minimized the testcase provided by @max-orhai a bit into the following gist: https://gist.github.com/robdockins/4959c81fe30723f8c5b3d2215db7feba

The problem appears to be with the handling of compositional verification lemmas in SAW; in particular, with choosing between multiple different lemmas for the same function.  If I run the same verification with no lemmas, the proof succeeds.  However, no combination of lemmas for `opt_eq` seems to currectly verify, even when they seem like they should be sufficient.  Moreover, some combinations give the above panic.

I'm inclined to believe this is a SAW bug, rather than a crucible bug. @brianhuffman, any ideas?

**Comment by robdockins** [comment]
Oops, not the one I meant.
